package app

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/dotcommander/pan/internal/config"
)

func TestBriefUsesOneProductionSliceForEntriesAndMap(t *testing.T) {
	root := t.TempDir()
	files := map[string]string{
		"main.go":                    "package main\nfunc Main() {}\n",
		"internal/service.go":        "package service\nfunc Run() {}\n",
		"internal/service_test.go":   "package service\nfunc TestRun() {}\n",
		"fixtures/sample.go":         "package fixtures\nfunc Sample() {}\n",
		".work/replay/receipt.jsonl": "{}\n",
		"generated/generated.go":     "// Code generated by fixture; DO NOT EDIT.\npackage generated\nfunc Generated() {}\n",
		"docs/notes.md":              "# notes\n",
		"data/fixture.json":          "{}\n",
	}
	for name, content := range files {
		path := filepath.Join(root, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
	}

	result, err := New(Deps{Config: config.Default()}).Brief(context.Background(), root, "run service", 10000)
	if err != nil {
		t.Fatal(err)
	}
	for _, entry := range result.Entries {
		if strings.Contains(entry.Path, ".work") || strings.Contains(entry.Path, "test") || strings.Contains(entry.Path, "fixture") || strings.Contains(entry.Path, "generated") {
			t.Errorf("non-production entry leaked: %q", entry.Path)
		}
	}
	for _, path := range []string{".work", "service_test.go", "fixtures", "generated", "docs", "data"} {
		if strings.Contains(result.Map.Text, path) {
			t.Errorf("non-production path %q leaked into brief map: %q", path, result.Map.Text)
		}
	}
	if !strings.Contains(result.Map.Text, "main.go") || !strings.Contains(result.Map.Text, "internal/service.go") {
		t.Fatalf("production files missing from brief map: %q", result.Map.Text)
	}
	if result.Map.TotalFiles != len(result.Entries) {
		t.Fatalf("brief entries/map disagree: entries=%d map_total=%d", len(result.Entries), result.Map.TotalFiles)
	}
}

func TestBriefIncompleteAnalysisIncludesEffectiveBoundsWithoutAnotherCommand(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "main.go"), []byte("package main\nfunc Main() {}\nfunc Run() {}\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	cfg := config.Default()
	cfg.MaxNodes = 1
	result, err := New(Deps{Config: cfg}).Brief(context.Background(), root, "main", 1000)
	if err != nil {
		t.Fatal(err)
	}
	if result.Coverage.Complete {
		t.Fatal("brief unexpectedly reported complete analysis")
	}
	if result.Coverage.Bounds.MaxNodes != 1 {
		t.Fatalf("effective max nodes = %d, want 1", result.Coverage.Bounds.MaxNodes)
	}
	for _, command := range result.NextCommands {
		if strings.Join(command.Args, " ") == "config print" {
			t.Fatalf("brief required redundant config call: %#v", result.NextCommands)
		}
	}
}
