package clean

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// tsPattern matches timestamp-like lines that indicate log dumps.
var tsPattern = regexp.MustCompile(`\d{4}-\d{2}-\d{2}[T ]|^\[\d{4}-\d{2}`)

// Classify reads the head and tail of small, ambiguous, non-symlink files
// and sets their Content classification. Classification is pure Go: no
// external tools are invoked and nothing is executed.
func Classify(files []FileInfo) {
	exts := classifyExts()
	for i := range files {
		f := &files[i]
		if f.IsDir || f.IsSymlink {
			continue
		}
		if f.Size <= 0 || f.Size >= 1<<20 {
			continue
		}
		if f.Content != ContentUnknown {
			continue
		}
		ext := filepath.Ext(f.Path)
		if ext != "" && !exts[ext] {
			continue
		}
		f.Content = classifyFile(f.Path, f.Size)
	}
}

// classifyExts returns the extensions whose content is inspected;
// everything else keeps ContentUnknown unless a finding needs no content
// hint.
func classifyExts() map[string]bool {
	return map[string]bool{
		".md": true, ".txt": true, ".json": true, ".yaml": true, ".yml": true,
		".go": true, ".ts": true, ".js": true, ".sh": true, ".py": true,
		".toml": true, ".cfg": true, ".ini": true,
	}
}

// classifyFile inspects the first 256 bytes and, when they differ, the last
// 256 bytes, and maps the sampled content onto a ContentClass.
func classifyFile(path string, knownSize int64) ContentClass {
	f, err := os.Open(path)
	if err != nil {
		return ContentUnknown
	}
	defer func() { _ = f.Close() }()

	head := readChunk(f)
	if len(head) == 0 {
		return ContentUnknown
	}
	return classifyContent(sampleContent(f, head, knownSize))
}

// readChunk reads up to 256 bytes at the current offset.
func readChunk(f *os.File) []byte {
	buf := make([]byte, 256)
	n, _ := f.Read(buf)
	return buf[:n]
}

// sampleContent builds the inspected text: for larger files the head plus
// the final chunk, for smaller files the head plus whatever follows it.
func sampleContent(f *os.File, head []byte, knownSize int64) string {
	if knownSize > 512 {
		_, _ = f.Seek(-256, io.SeekEnd)
		if tail := readChunk(f); len(tail) > 0 {
			return string(head) + string(tail)
		}
		return string(head)
	}
	if more := readChunk(f); len(more) > 0 {
		return string(head) + string(more)
	}
	return string(head)
}

// classifyContent maps sampled text onto a ContentClass using generated
// markers, scratch-line shapes, timestamp density, and config shapes.
func classifyContent(data string) ContentClass {
	lower := strings.ToLower(data)
	if looksGenerated(data, lower) {
		return ContentGenerated
	}
	lines := splitLines(data)
	if len(lines) == 0 {
		return ContentMeaningful
	}
	switch {
	case allScratchLines(lines):
		return ContentTodoOnly
	case majorityTimestamps(lines):
		return ContentLogDump
	case configShaped(lines):
		return ContentConfig
	}
	return ContentMeaningful
}

func looksGenerated(data, lower string) bool {
	return strings.Contains(data, "Code generated") ||
		strings.Contains(data, "AUTO-GENERATED") ||
		strings.Contains(data, "Auto-generated") ||
		strings.Contains(data, "DO NOT EDIT") ||
		strings.Contains(data, "do not edit") ||
		strings.Contains(lower, "generated by")
}

func majorityTimestamps(lines []string) bool {
	matches := 0
	for _, l := range lines {
		if tsPattern.MatchString(l) {
			matches++
		}
	}
	return matches*2 > len(lines)
}

// configShaped reports whether the sampled text looks like structured
// configuration: JSON/YAML/front-matter shapes or a majority of
// key-value lines.
func configShaped(lines []string) bool {
	firstLine := strings.TrimSpace(lines[0])
	if strings.HasPrefix(firstLine, "{") || strings.HasPrefix(firstLine, "---") {
		return true
	}
	if strings.HasPrefix(firstLine, "[") && !strings.Contains(firstLine, "](") {
		return true
	}
	return majorityKVLines(lines)
}

func majorityKVLines(lines []string) bool {
	kvCount := 0
	for _, l := range lines {
		if isKVLine(l) {
			kvCount++
		}
	}
	return kvCount*2 > len(lines)
}

func splitLines(data string) []string {
	raw := strings.Split(data, "\n")
	out := make([]string, 0, len(raw))
	for _, l := range raw {
		if strings.TrimSpace(l) != "" {
			out = append(out, l)
		}
	}
	return out
}

func allScratchLines(lines []string) bool {
	prefixes := scratchPrefixes()
	for _, l := range lines {
		if !matchesScratchPrefix(l, prefixes) {
			return false
		}
	}
	return true
}

func matchesScratchPrefix(line string, prefixes []string) bool {
	trimmed := strings.TrimSpace(line)
	for _, p := range prefixes {
		if strings.HasPrefix(trimmed, p) {
			return true
		}
	}
	return false
}

// scratchPrefixes returns the line prefixes that mark scratch or notes
// content.
func scratchPrefixes() []string {
	return []string{"TODO", "FIXME", "HACK", "XXX", "- [ ]", "- [x]", "- [X]"}
}

func isKVLine(l string) bool {
	trimmed := strings.TrimSpace(l)
	if idx := strings.Index(trimmed, ": "); idx > 0 {
		key := trimmed[:idx]
		if !strings.Contains(key, " ") && len(key) < 40 {
			return true
		}
	}
	if idx := strings.Index(trimmed, " = "); idx > 0 {
		key := trimmed[:idx]
		if !strings.Contains(key, " ") && len(key) < 40 {
			return true
		}
	}
	return false
}

// Bounds for the pure-Go referenced-script search.
const (
	maxReferenceFiles     = 2000
	maxReferenceFileBytes = 4 << 20
	maxReferenceTotal     = 64 << 20
)

// referencedScripts reports which of names appear anywhere in bounded reads
// of referenceable files under root. The search is pure Go: no grep, no
// shell, no execution.
func referencedScripts(root string, names []string) map[string]bool {
	if len(names) == 0 {
		return nil
	}
	search := &referenceSearch{
		root:      root,
		names:     names,
		exts:      referenceableExts(),
		fileNames: referenceableNames(),
		remaining: maxReferenceTotal,
		found:     make(map[string]bool),
	}
	_ = filepath.WalkDir(root, search.visit)
	return search.found
}

// referenceableExts and referenceableNames select the files searched for
// script references, matching the source, documentation, and task-runner
// surfaces where a root script would be invoked.
func referenceableExts() map[string]bool {
	return map[string]bool{".go": true, ".md": true, ".yml": true, ".yaml": true}
}

func referenceableNames() map[string]bool {
	return map[string]bool{makefileName: true, "justfile": true, "Justfile": true}
}

// referenceSearch carries the bounded walk state for one referenced-script
// scan.
type referenceSearch struct {
	root      string
	names     []string
	exts      map[string]bool
	fileNames map[string]bool
	remaining int
	visited   int
	found     map[string]bool
}

// visit skips unreadable entries and delegates everything else.
func (s *referenceSearch) visit(path string, d os.DirEntry, err error) error {
	if err == nil {
		return s.visitEntry(path, d)
	}
	return nil
}

func (s *referenceSearch) visitEntry(path string, d os.DirEntry) error {
	if s.visited >= maxReferenceFiles || s.remaining <= 0 {
		if d.IsDir() {
			return filepath.SkipDir
		}
		return nil
	}
	if d.IsDir() {
		return s.visitDir(path, d)
	}
	if s.isReferenceable(d) {
		s.visitFile(path, d)
	}
	return nil
}

// visitDir prunes hidden and dependency directories below the root.
func (s *referenceSearch) visitDir(path string, d os.DirEntry) error {
	if path != s.root && (strings.HasPrefix(d.Name(), ".") || d.Name() == "node_modules") {
		return filepath.SkipDir
	}
	return nil
}

func (s *referenceSearch) isReferenceable(d os.DirEntry) bool {
	if s.exts[filepath.Ext(d.Name())] {
		return true
	}
	return s.fileNames[d.Name()]
}

// visitFile scans one referenceable regular file within the byte budget.
func (s *referenceSearch) visitFile(path string, d os.DirEntry) {
	info, statErr := d.Info()
	if statErr != nil || !info.Mode().IsRegular() || info.Size() == 0 {
		return
	}
	s.visited++
	limit := min(int64(s.remaining), int64(maxReferenceFileBytes))
	found, used := containsAnyName(path, s.names, limit)
	s.remaining -= used
	for name := range found {
		s.found[name] = true
	}
}

// containsAnyName reads at most limit bytes from path and reports which of
// names occur in the sampled text, along with how many bytes were read.
func containsAnyName(path string, names []string, limit int64) (map[string]bool, int) {
	f, err := os.Open(path)
	if err != nil {
		return nil, 0
	}
	defer func() { _ = f.Close() }()
	data, err := io.ReadAll(io.LimitReader(f, limit))
	if err != nil {
		return nil, 0
	}
	text := string(data)
	found := make(map[string]bool)
	for _, name := range names {
		if strings.Contains(text, name) {
			found[name] = true
		}
	}
	return found, len(data)
}

// fmtSize renders byte sizes for review comments.
func fmtSize(b int64) string {
	const unit = 1024
	if b < unit {
		return fmt.Sprintf("%dB", b)
	}
	div, exp := int64(unit), 0
	for n := b / unit; n >= unit; n /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f%cB", float64(b)/float64(div), "KMGTPE"[exp])
}
