package improve

import (
	"context"
	"os"
	"path/filepath"
	"testing"
)

func TestMeasureStructuralProposalDoesNotPayForFormattingOrComments(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeFile(t, root, "go.mod", fixtureGoMod)
	old := "package demo\n\n// helper documents the helper.\nfunc helper() int { return 1 }\n"
	writeFile(t, root, "demo.go", old)
	formatted := "package demo\n\n// rewritten documentation.\nfunc helper() int {\n\treturn 1\n}\n"

	metrics, err := MeasureStructuralProposal(context.Background(), root, []FileChange{{FilePath: "demo.go", NewContents: formatted}})
	if err != nil {
		t.Fatal(err)
	}
	if metrics.NetSymbolReduction != 0 || metrics.Fee(true, 0.5) != 0 {
		t.Fatalf("format/comment-only metrics = %+v, fee=%v", metrics, metrics.Fee(true, 0.5))
	}
}

func TestMeasureStructuralProposalPaysOnlyForRemovedSymbols(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeFile(t, root, "go.mod", fixtureGoMod)
	writeFile(t, root, "demo.go", "package demo\n\nfunc keep() {}\n\nfunc remove() {}\n")

	metrics, err := MeasureStructuralProposal(context.Background(), root, []FileChange{{FilePath: "demo.go", NewContents: "package demo\n\nfunc keep() {}\n"}})
	if err != nil {
		t.Fatal(err)
	}
	if metrics.SymbolsDeleted != 1 || metrics.SymbolsAdded != 0 || metrics.SymbolsModified != 0 || metrics.NetSymbolReduction != 1 {
		t.Fatalf("metrics = %+v", metrics)
	}
	if got := metrics.Fee(true, 0.25); got != 0.25 {
		t.Fatalf("fee = %v, want 0.25", got)
	}
}

func TestMeasureStructuralProposalExcludesGeneratedAndVendorSources(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeFile(t, root, "go.mod", fixtureGoMod)
	writeFile(t, root, "generated.go", "// Code generated by fixture DO NOT EDIT.\n\npackage demo\n\nfunc remove() {}\n")
	writeFile(t, root, "vendor/example/vendor.go", "package vendor\n\nfunc remove() {}\n")

	metrics, err := MeasureStructuralProposal(context.Background(), root, []FileChange{
		{FilePath: "generated.go", NewContents: "package demo\n"},
		{FilePath: "vendor/example/vendor.go", NewContents: "package vendor\n"},
	})
	if err != nil {
		t.Fatal(err)
	}
	if metrics != (StructuralMetrics{}) {
		t.Fatalf("excluded metrics = %+v", metrics)
	}
}

func TestProposalPathsCannotTraverseSymlinks(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	outside := t.TempDir()
	outsideFile := filepath.Join(outside, "escape.go")
	if err := os.WriteFile(outsideFile, []byte("package outside\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(outside, filepath.Join(root, "linked")); err != nil {
		t.Fatal(err)
	}
	change := FileChange{FilePath: "linked/escape.go", NewContents: "package outside\n\nfunc changed() {}\n"}
	if err := ValidateProposal(root, []FileChange{change}); err == nil {
		t.Fatal("ValidateProposal accepted a symlink traversal")
	}
	if err := ApplyProposal(root, []FileChange{change}); err == nil {
		t.Fatal("ApplyProposal accepted a symlink traversal")
	}
	contents, err := os.ReadFile(outsideFile)
	if err != nil {
		t.Fatal(err)
	}
	if string(contents) != "package outside\n" {
		t.Fatalf("outside target was mutated: %q", contents)
	}
}
